language: go

go:
  - 1.15.x

install:
  - go get -t -v ./...


script:
  - go test -coverprofile=coverage.txt -covermode=atomic
  - |
    for GOOS in linux darwin windows;do
      suffix=""
      if [ $GOOS == "windows" ];
      then
        suffix=".exe"
      fi
      for GOARCH in 386 amd64;do
        out="bin/tagfmt${suffix}"
        echo "building ${GOOS}/$GOARCH"
        CGOENABLE=0 go build -o $out
        if [ $GOOS == "windows" ];
        then
          compress="bin/tagfmt_${GOOS}_${GOARCH}.zip"
          echo "compressing $compress"
          zip $compress $out
          rm $out
        else
          compress="bin/tagfmt_${GOOS}_${GOARCH}.tar.gz"
          echo "compressing $compress"
          tar czf $compress $out --remove-files
        fi
      done
    done
after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  file: bin/*
  file_glob: true
  api_key: $GITHUB_TOKEN
  on:
    tags: true
    repo: bigpigeon/tagfmt
    branch: master
  skip_cleanup: true
  #overwrite: true
  #file_glob: true