language: go

go:
  - 1.15.x

install:
  - go get -t -v ./...


script:
  - |
    for OS in linux darwin windows;do
      suffix=""
      if [ $OS == "windows" ];
      then
        suffix=".exe"
      fi
      for GOARCH in 386 amd64;do
        out="bin/tagfmt_${OS}_${GOARCH}${suffix}"
        echo "building $out"
        go build -o $out
      done
    done
  - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  file: bin/*
  file_glob: true
  api_key: $GITHUB_TOKEN
  on:
    tags: true
    repo: bigpigeon/tagfmt
    branch: master
  skip_cleanup: true
  #overwrite: true
  #file_glob: true